#
# Deploy login to kubernetes vultr.
#
# NOTE: for this to work you'll need to configure a personal access token in K8s/Github.
# Information about doing that can be found here: https://stackoverflow.com/questions/72959144/k8s-to-pull-private-image-from-github-container-registry-ghcr-using-github-tok
#
# kubectl create secret docker-registry ghcr-login-secret --docker-server=https://ghcr.io --docker-username=$YOUR_GITHUB_USERNAME --docker-password=$YOUR_GITHUB_TOKEN --docker-email=$YOUR_EMAIL
#
# The secret name given in the above command is then specified in 'imagePullSecrets' in the specification.
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pkce
  name: pkce
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: pkce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkce
  labels:
    app: pkce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pkce
  template:
    metadata:
      labels:
        app: pkce
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: pkce
          image: ghcr.io/commandquery/pkce:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PKCE_ISSUER
              value: "https://hello.coachcentric.online"
            - name: PKCE_CLIENT_ID
              value: "255702049671421989@coachcentric"
            - name: PKCE_BASE
              value: "https://hello.coachcentric.online/pkce"
            - name: PKCE_DOMAIN
              value: "coachcentric.online"
            - name: PKCE_SECURE
              value: "true"
            - name: PKCE_REDIRECT
              value: "https://app.coachcentric.online/home"
            - name: PKCE_PREFIX
              value: "/pkce"
            - name: PKCE_COOKIE
              value: "Authorization"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pkce
spec:
  tls:
    - hosts:
        - hello.coachcentric.online
      secretName: cert-hello-coachcentric-online
  rules:
  - host: hello.coachcentric.online
    http:
      paths:
      - path: /pkce
        pathType: Prefix
        backend:
          service:
            name: pkce
            port:
              number: 8081
