name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true

      - name: Install dependencies
        run: |
          go get

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o pkce

      - name: Docker
        run: |
          docker build -t ghcr.io/commandquery/pkce -f Dockerfile .

      - name: Publish
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u doctor-eval --password-stdin
          docker push ghcr.io/commandquery/pkce:latest



#      - name: Test
#        run: go test -v ./...
